[platformio]
; Set Brutos as the active project when operating from workspace root.
default_envs = brutos
extra_configs = Brutos/platformio.ini
src_dir = Brutos/src
include_dir = Brutos/include
lib_dir = Brutos/lib
test_dir = Brutos/test
